databases:
  - name: realtime_4esr
    databaseName: realtime_4esr
    user: realtime_4esr_user

services:
  - type: web
    name: realtimesearch
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: realtime_4esr_user
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false